aquaR
=================
This package was created to speed up certain analyses in aquaculture research with focus on plotting results. This package is work in progress and new functions will be added and edited in the future.

### install
with `devtools`:
```S
library(devtools)
install_github("gtimmerhaus/aquaR")
```
### use
Overview over the available functions so far:

General functions:

1. sterr: calculated the standard error for the imput data vector.
2. TGC_calculation: Calcualte the thermal growth coefficient
3. barplot.col: Plots a barplot with means of the data according to the group vector and addes error bars.
4. plot.err: Similar to barplot.col but dots are plotted instead of bars.
5. plot.err.time: similar to plot.err but made for time series in addition to groups.
6. plot.err.two.factor: Plot group data in the background (group1) and subgroups (group2) in the foreground with error bars.

Functions for temperature dependent maximum heart rate analysis:

7. HR.plot: a specialized plot for for visualization and analysis of hear rate data.
8. q10: calculated the Q10 values for heart rate breakpoint analysis.
9. breakPointsQ10: plots and calcualtes the breakpoints for optimum temperature according to Q10 values
10. breakPointsArrhenius: plots and calcualtes the breakpoints for optimum temperature according to Arrhenius' method 

