---
title: "aquaR"
author: "Gerrit Timmerhaus"
maintainer: "Gerrit Timmerhaus <gerrit.timmerhaus@gmail.com>"
version: 1.0
date: "Thursday, January 21, 2016"
output: pdf_document
---

# aquaR: Plots and funtions for aquaculture research

## Introduction

This package is work in progress and currently contains functions which plot and run basic statistics on given data, as it is commonly used in aquaculture and fish research.

## Funtions

***

> **sterr**

### Description

Calculates the standard error of a given numeric vector. It is called from most functions in this package.

### Usage

```
sterr(x)
```

### Arguments

argument    |   description
----------- | --------------
x           |   numeric vector. NAs will be removed before cacluation.


### Examples

```
x <- c(2,3,4,NA,3,2,0)
sterr(x)
```

***

> **plot.err**

### Description

Plot the means of a numeric vector, grouped by a group vector. ± standard error bars or standard deviation error bars are added to the plotted means. ANOVA results can be added optionally.

### Usage

```
plot.err(data = x, groups = g, ...)
```

### Arguments

argument    |   description
----------- | --------------
data        |   numeric vector. NAs are allowed and will be removed for mean cacluation.
group       |   group vector defining the groups in data. 
type        |   one of "dot", "bar" or "diffbar" for mean value representation as dots, 
.           |   bars or bars which are centered around the overall mean. 
err.bars    |   one of "sterr" (default) or "sd". Defines if error bars should represent 
.           |   ± standard error or standard deviaton. 
length      |   defines the legnth of the heads of the error bars.
lwd         |   defines the line width of error bars.
barwidth    |   defines the width of bars.
col         |   vector of equal length as number of groups, containing the desired colors.
at          |   optinal to adjust the x-position of the means in the plot.
cex         |   defines size of dots.
xlab        |   set x-axis label.
ylab        |   set y-axis label.
xaxt        |   if TRUE (default) the x-axis will be added to the plot.
main        |   adds a title to the plot.
las.x       |   either 1 or 2. text orientation of the x-axis labels.
las.y       |   either 1 or 2. text orientation of the y-axis labels.
cex.yaxis   |   scaling for y-axis labels.
cex.xaxis   |   scaling for x-axis labels.
yscale      |   vector of length two to set the y-axis upper and lower limits.
stats       |   add ANOVA results to the plot.
stats.mark  |   add stars to significant ANOVA results.
sig.groups  |   vector with significance marker (e.g. Tukey groups), which will be places 
.           |   over the error bars (order is 1:n and not according to at!)



### Examples

```
plot.err(data=c(1,2,3,5,3,2,4,12), groups = c(rep("a",4),rep("b",4)))
```








You can also embed plots, for example:

```{r, echo=FALSE}
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
